### ISSUE TITLE
Use our libiconv

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/git-feedstock#16]
On OS X, it appears to be getting `libiconv` from the system. This is evidenced when fixing paths in Travis CI build [log](https://travis-ci.org/conda-forge/git-feedstock#L1316). However, adding our `libiconv` is not sufficient. As can be seen by this Travis CI build [log](https://travis-ci.org/conda-forge/git-feedstock/builds/153169956#L1294-L1297), our version of `libiconv` does not provide an acceptable ABI. Thus we may need to build a newer version of `libiconv` to fix this issue.

**Comment by ostrokach** [comment]
I get the error:

```
git: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory
```

when trying to run `git` from conda-forge on centos:6.

**Comment by dougalsutherland** [comment]
This was fixed at some point; e.g. [latest build on `master`](https://travis-ci.org/conda-forge/git-feedstock/jobs/395492963).
