### ISSUE TITLE
missing git manpages

### ISSUE THREAD

**Issue by chicagofire** [conda-forge/git-feedstock#17]
The recipe doesn't seem to include the git manpages in the build.

**Comment by msarahan** [comment]
This is something of a fault with the conda ecosystem as a whole.  man pages are almost never distributed with conda packages.  I don't know what it would take to have a man executable ship with conda that knew where to look.  You might want to propose that on the conda-forge/staged-recipes issue tracker, or perhaps on conda/conda itself.

**Comment by chicagofire** [comment]
At least on Redhat Enterprise Linux[567], man will supplement the MANPATH
with man directories near your PATH entries, so, man on the host is still
able to find the man files if you install them in <conda-env>/man and I
have activated that environment. This is certainly better than not having
the man pages at all.

**Comment by jakirkham** [comment]
Yeah, `MANPATH` would be a way to do this. Building `man` shouldn't be too difficult either based on [this]( http://www.linuxfromscratch.org/lfs/view/development/chapter06/man-db.html ). Actually there was some discussion about whether or not to keep manpages and other stuff in general in issue ( https://github.com/conda-forge/staged-recipes/issues/673 ). Would be great to have both of you weigh in.

**Comment by timsnyder** [comment]
This will keep me from being able to widely use the conda-forge git package.  My userbase depends on being able to get help for commands using `--help`, which git handles as `man git-<command>`.  I chimed in with a :+1: on the conda-forge/staged-recipes#673 comment about the manpages.

**Comment by asmeurer** [comment]
See https://github.com/conda/conda/issues/845

**Comment by timsnyder** [comment]
When I asked about docs during the conda-forge BoF at SciPy this summer, @scopatz quickly replied about docs packages being an antipattern.  That made me think this had been resolved (by including the manpages).  I'm building a new environment for my users and while doing some QA checks, it looks like git from defaults and conda-forge is still missing manpages.

Is there a chance that a PR would be accepted for this?

**Comment by scopatz** [comment]
yep, I would accept a PR to add this!

**Comment by timsnyder** [comment]
So, here's a question.  Building the manpages uses `asciidoc` then `xmlto`.  `asciidoc` isn't an issue. `conda-forge` already has it.  However, I'm being reminded how much of a rabbit hole `xmlto` is.

The git project has been shipping prebuilt manpage tarballs from https://mirrors.edge.kernel.org/pub/software/scm/git/ for quite awhile.

Of the three options, which would be best:
1. Package the prebuilt manpages
1. Dive into adding recipes for `xmlto` and what it needs to produce man output.
1. Add xmlto into the git-feedstock's yum-requirements.txt.  

I'm thinking that using the prebuilt manpages makes the most sense.

**Comment by msarahan** [comment]
1 seems reasonable to me. Should be easy with multiple sources in the recipe. 2 would be my next preferred thing.

**Comment by scopatz** [comment]
1 also seems reasonable.

**Comment by timsnyder** [comment]
My upcoming PR only adds the manpages for `[not win]` platforms.  

I downloaded and confirmed that on Windows the repackaged PortableGit launches HTML help when asking for `git clone --help`.

**Comment by scopatz** [comment]
Sounds good!
