### ISSUE TITLE
Full Git

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/git-feedstock#31]
The [PortableGit](https://github.com/git-for-windows/git/releases) build is currently used on Windows which is just enough to run Git itself. Whenever I install git manually I always choose to install all the Unix tools as well as they're very useful. The build which includes all the optional Unix tools is:
```
https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/Git-{{ version }}-64-bit.tar.bz2
```
e.g.
![image](https://user-images.githubusercontent.com/881019/34025152-0af2071e-e19a-11e7-9395-c783c85da0fd.png)

It would be good to be able to install the full version of git (with unix tools) on Windows. I'm not sure though if conda has a good way to select optional features? If not perhaps consideration could be given to just packaging the full git by default...

**Comment by msarahan** [comment]
Yes, it is much better to use m2 packages, though I think git is pretty out of date right now.  Having everything bundled in with git makes for some really awkward situations when the tools packaged with git conflict with other tools.  It is very important to make every package contain only exactly what it needs, and make other packages for the other tools you need.

**Comment by dhirschfeld** [comment]
Sounds good - I wasn't too familiar with the `m2` packages as I usually just install Git manually with the installer.

I was wanting to switch to the conda version to make deploying on Windows Containers easier. One thing I'm interested in is setting git to use the Secure Channel library so I'm not sure how I could do that with the conda packages.

![image](https://user-images.githubusercontent.com/881019/34026923-0f4f124c-e1a5-11e7-818c-7cfd9dc0b4fe.png)


[This](https://groups.google.com/forum/#!topic/git-for-windows/X1WucxvJdGQ) message seems to suggest it's just a matter of swapping out the curl implementation but I can't seem to see the `<Git>\mingw64\curl-winssl\` directory they talk about :confused:

**Comment by dhirschfeld** [comment]
Maybe my use case is specialised enough that I should stick with a custom install...

**Comment by dhirschfeld** [comment]
Closing as the better solution is to use the `m2-` packages.
