### ISSUE TITLE
Busybox MinGit

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/git-feedstock#32]
The "normal" git has a bug when used in a host mapped volume from within a container. The BusyBox MinGit doesn't suffer from the same issue.

https://github.com/git-for-windows/git/issues/1403#issuecomment-355429601

https://github.com/git-for-windows/git/issues/1007

**Comment by jakirkham** [comment]
Feel free to add a different package for git on Windows at `staged-recipes`. Maybe `mingit` as a name?

**Comment by msarahan** [comment]
Anaconda switched to mingit with busybox a little while ago.  Our recipe is at https://github.com/anacondarecipes/git-feedstock

The full git4win was causing us headaches having all the other unix stuff tied in with git.  Separating that out and asking people to use ``m2-*`` is a better way.

**Comment by jakirkham** [comment]
So what’s gained with MinGit vs. just using `m2-git`?

**Comment by dhirschfeld** [comment]
Thanks @msarahan - I'll have to figure out how to pin git to the defaults channel then...

**Comment by msarahan** [comment]
@jakirkham m2-git would be ideal, but it's out of date, and @mingwandroid has been too busy with other things to get the m2 recipes building from source and/or updated to more current msys2 releases.

``m2-git`` and mingit ideally would be roughly equivalent, I think, provided they were both at the same version.  I think @mingwandroid would probably add perl as a dependency to m2-git, though, so the overall install size of m2-git plus deps might be significantly larger.  Perl is currently necessary for several interactive git commands, such as ``git add -p``

**Comment by mingwandroid** [comment]
The git executable in m2-git is not native, it uses the msys2-runtime (cygwin fork) and so is a little slower that official git executables (though not enough that it's ever bothered me).

But it's quite old, yeah.

**Comment by dhirschfeld** [comment]
Since MinGit is a different distribution with different capabilities than the full git I agree it should prob be a different package so I'll close this issue and prob just use the defaults now I know it's the Busybox version

**Comment by dscho** [comment]
@msarahan oh, that's interesting. I wondered whether anybody had time to test this. Could you maybe say a few things about your experience with BusyBox-based MinGit?

**Comment by msarahan** [comment]
@dscho MinGit works well for me, but I must say I don't use it very heavily.  I do most of my git work on my Mac, and build on a win VM with that Mac's files shared into the win VM.  The specific problems we were having were bizarre incompatibility with Concourse (windows workers being unable to communicate with master server due to incompatibility with tar.exe somehow), and confusion/clobbering of those unix exe's with MSYS2 packages.
