### ISSUE TITLE
Windows builds corrupt (I removed them)

### ISSUE THREAD

**Issue by msarahan** [conda-forge/git-feedstock#4]
they were 18 kB or so.  Definitely wrong.  I removed them from anaconda.org so they won't trip anyone up.  The win build needs work - it definitely should fail if its packages are corrupt like this.

**Comment by jakirkham** [comment]
That sounds like a good plan. Should we disable Windows builds at present until we get this fixed?

**Comment by msarahan** [comment]
yes, that sounds like a good idea.

**Comment by jakirkham** [comment]
I would rerender, but our Mac builds are now failing due to the header path length. Weird as this didn't hit us before, but it is now.

**Comment by jakirkham** [comment]
Seems there was an issue with the build script here. Added a test and a fix in this PR ( https://github.com/conda-forge/git-feedstock/pull/11 ).
