### ISSUE TITLE
team members

### ISSUE THREAD

**Issue by pelson** [conda-forge/git-feedstock#5]
Curious issue on https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/126790505: 

```
Running command: ['python', '/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_teams.py', './feedstocks_repo/feedstocks']
AN OLD MEMBER (msarahan) NEEDS TO BE REMOVED FROM conda-forge/git-feedstock
AN OLD MEMBER (pelson) NEEDS TO BE REMOVED FROM conda-forge/git-feedstock
```

Not sure how the team was populated originally, but it appears to be out of sync with the recipe maintainers list.

**Comment by jakirkham** [comment]
Yeah, that is pretty strange. Was just looking at that. Though in the whole history of this feedstock, I have been the only maintainer. Do you guys wanted to be added @pelson and @msarahan?

**Comment by jakirkham** [comment]
> Do you guys wanted to be added @pelson and @msarahan?

Oops 😳 , we have had this conversation before ( https://github.com/conda-forge/git-feedstock/pull/2 ). I'm going to try restarting the CIs to see if the issues persist in this PR ( https://github.com/conda-forge/git-feedstock/pull/3 ).

**Comment by jakirkham** [comment]
Nope still doesn't work. Still hitting max path length issue.

**Comment by jakirkham** [comment]
As curious as this was, both of you are now team members @pelson and @msarahan. So, will mark this as resolved.
