### ISSUE TITLE
No PR for v2.24.1 

### ISSUE THREAD

**Issue by tpdownes** [conda-forge/git-feedstock#72]
No PR has been created for the [2.24.1 release of git](https://github.com/git/git/releases/tag/v2.24.1).

What is a little bit weird is that the GitHub repo no longer appears to have a tag/release for v2.24.0, the current conda-forge release of `git`. Is it possible for the bot that auto-creates PRs to be confused when a release/tag disappears?

**Comment by scopatz** [comment]
Yeah, the bot could be confused in circumstances like this.  A more recent version of git has come out, though

**Comment by tpdownes** [comment]
Hrm. It appears that the `git` repo is *always* removing old patch-release tags. So it maintains the latest `z` in `x.y.z` but removes older values of `z`. That... is weird but perhaps something to consider. I think `conda-forge` is missing a lot of interim patch releases of `git`.

**Comment by tpdownes** [comment]
Will close and you can consider how whether this is an issue and file your own.
