### ISSUE TITLE
Recipe uses wrong ca-files according to conda documentation

### ISSUE THREAD

**Issue by domste** [conda-forge/git-feedstock#82]
According to [conda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/non-standard-certs.html) if `REQUESTS_CA_BUNDLE` is set should be used as default store. 

In the configuration the default conda ca-files are used and `REQUESTS_CA_BUNDLE ` is not considered.

https://github.com/conda-forge/git-feedstock/blob/14c0381b07d008a73e88ee8ca64631d499340b48/recipe/build.sh#L36

**Comment by scopatz** [comment]
PRs welcome

**Comment by j-4** [comment]
Hello, I hope this PR is fine like that. If I did something wrong or there is still something missing, please say so :-)

**Comment by domste** [comment]
The fix is not working, because the correct certificate path is set during build time and not during installation. I created a new PR #84 .
